# Generated by Django 4.1 on 2022-08-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Wing',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_material', models.FileField(upload_to='course_materials')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wing.wing')),
            ],
            options={
                'verbose_name': 'Course',
                'ordering': ('-upload_date',),
            },
        ),
    ]
