# Generated by Django 4.1 on 2022-08-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='course',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterIndexTogether(
            name='wing',
            index_together={('id', 'slug')},
        ),
    ]
