# Generated by Django 4.1 on 2022-08-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-upload_date',), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
