# Generated by Django 4.1 on 2022-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.TextField(max_length=200)),
                ('staff_title', models.TextField(max_length=200)),
                ('staff_accomplishments', models.TextField(blank=True, max_length=200)),
                ('staff_image', models.ImageField(upload_to='staff_images')),
            ],
        ),
    ]
