# Generated by Django 4.1 on 2022-08-19 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staffpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('Name',), 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_title',
        ),
        migrations.AddField(
            model_name='staff',
            name='Appointment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='Rank',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_accomplishments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
